#!/usr/bin/env bash
set -euo pipefail
shopt -s nullglob

# refuse to start under an outdated docker-zeek executable
if [[ -d /zeek ]] || mountpoint -q /root/.zkg 2>/dev/null; then
	cat >&2 <<'EOF'
=================================================================
This image requires docker-zeek __VERSION__.

The previous version of docker-zeek installed on this
system is not compatible with this image.

To upgrade, install docker-zeek __VERSION__ from:
    https://github.com/activecm/docker-zeek/releases/tag/__VERSION__
=================================================================
EOF
	exit 1
fi

# refuse to start if local.zeek is mounted from the host
if mountpoint -q /usr/local/zeek/share/zeek/site/local.zeek 2>/dev/null; then
	cat >&2 <<'EOF'
error: local.zeek is bind-mounted from the host. This image generates local.zeek
at every start from share/zeek/site/autoload/, so the mount would be overwritten.

To add custom Zeek code, use a separate file in share/zeek/site/autoload/.
Remove the local.zeek mount from your docker-compose file or docker run command.
EOF
	exit 1
fi


# set node.cfg path
NODE_CFG=/usr/local/zeek/etc/node.cfg

# function to generate node.cfg from selected interfaces
generate_node_cfg() {
	IFS=',' read -ra raw_ifaces <<< "${ZEEK_INTERFACE}"
	local ifaces=()
	for i in "${raw_ifaces[@]}"; do
		i="${i// /}"
		[[ -n "$i" ]] && ifaces+=("$i")
	done
	if [[ ${#ifaces[@]} -eq 0 ]]; then
		echo "error: ZEEK_INTERFACE is set but contains no valid interface names." >&2
		exit 1
	fi

	local num_ifaces=${#ifaces[@]}
	local total_workers
	if [[ -n "${ZEEK_WORKERS:-}" ]]; then
		total_workers=${ZEEK_WORKERS}
	else
		# reserve 4 cores for OS, manager, proxy, logger
		total_workers=$(($(nproc) - 4))
	fi
	[[ $total_workers -lt $num_ifaces ]] && total_workers=$num_ifaces
	local per_iface=$((total_workers / num_ifaces))

	{
		echo "# Generated by docker-zeek __VERSION__"
		echo "# DO NOT EDIT THIS FILE"
		echo
		echo "[logger]"
		echo "type=logger"
		echo "host=localhost"
		echo
		echo "[manager]"
		echo "type=manager"
		echo "host=localhost"
		echo
		echo "[proxy-1]"
		echo "type=proxy"
		echo "host=localhost"
		local idx=0
		for iface in "${ifaces[@]}"; do
			local fanout_id
			if [[ $num_ifaces -eq 1 ]]; then
				fanout_id=23
			else
				fanout_id=$idx
			fi
			echo
			echo "[worker-${iface}]"
			echo "type=worker"
			echo "host=localhost"
			echo "interface=af_packet::${iface}"
			echo "lb_method=custom"
			echo "lb_procs=${per_iface}"
			echo "af_packet_fanout_id=${fanout_id}"
			echo "af_packet_fanout_mode=AF_Packet::FANOUT_HASH"
			echo "af_packet_buffer_size=128*1024*1024"
			idx=$((idx + 1))
		done
	} > "${NODE_CFG}"
}

missing_interface_help() {
	cat >&2 <<'EOF'
error: node.cfg not found. mount one in:

    docker run -v ./node.cfg:/usr/local/zeek/etc/node.cfg \
        --net=host --cap-add=NET_RAW --cap-add=NET_ADMIN activecm/zeek:__IMAGE_TAG__

Or set ZEEK_INTERFACE:

    docker run -e ZEEK_INTERFACE=eth0 --net=host \
        --cap-add=NET_RAW --cap-add=NET_ADMIN activecm/zeek:__IMAGE_TAG__

Minimal node.cfg example:
    [zeek]
    type=standalone
    host=localhost
    interface=eth0

Visible interfaces in this container:
EOF
	local found=0
	for n in /sys/class/net/*; do
		local name="${n##*/}"
		case "$name" in
			lo|br-*|veth*|virbr*|docker*) continue;;
		esac
		echo "    $name" >&2
		found=1
	done
	if [[ $found -eq 0 ]]; then
		echo "    (none detected; you may need --net=host)" >&2
	fi
}

# verify node.cfg exists and is non-empty, otherwise generate it from ZEEK_INTERFACE
# if neither is available, print error and exit
if [[ -f "${NODE_CFG}" && -s "${NODE_CFG}" ]]; then
	:
elif [[ -n "${ZEEK_INTERFACE:-}" ]]; then
	generate_node_cfg
else
	missing_interface_help
	exit 1
fi

stop() {
	echo "stopping zeek..."
	zeekctl stop
	exit 0
}
trap stop SIGINT SIGTERM

# disable NIC offloading on monitored interfaces for accurate packet capture.
# parse unique interfaces from node.cfg, stripping af_packet:: prefix if present.
# errors are non-fatal since some flags may not be supported on all NICs or VMs.
declare -A seen_ifaces
while IFS='=' read -r key value; do
	[[ "$key" =~ ^[[:space:]]*interface ]] || continue
	iface="${value##af_packet::}"
	iface="${iface// /}"
	[[ -n "$iface" ]] || continue
	[[ -z "${seen_ifaces[$iface]+x}" ]] || continue
	seen_ifaces[$iface]=1
	if ethtool -K "$iface" rx off tx off sg off tso off gso off gro off lro off >/dev/null 2>&1; then
		echo "disabled NIC offloading on $iface"
	else
		echo "warning: failed to disable some offloading features on $iface (this may be expected in virtual environments)" >&2
	fi
done < /usr/local/zeek/etc/node.cfg

# build local.zeek from autoload scripts, stripping comments
autoload=(/usr/local/zeek/share/zeek/site/autoload/*.zeek)
if [[ ${#autoload[@]} -eq 0 ]]; then
	echo "error: no .zeek scripts found in autoload directory" >&2
	exit 1
fi
grep -hv '^#' "${autoload[@]}" > /usr/local/zeek/share/zeek/site/local.zeek

zeekctl check || { echo "error: zeek configuration check failed" >&2; exit 1; }
zeekctl install || { echo "error: zeekctl install failed" >&2; exit 1; }

# replace zeekctl's absolute symlink with a relative one so /opt/zeek/logs/current
# resolves correctly from the host
target=$(readlink /usr/local/zeek/logs/current 2>/dev/null || true)
if [[ -n "$target" ]]; then
	ln -sfn "../spool/$(basename "$target")" /usr/local/zeek/logs/current
fi

# start zeek
zeekctl start || { echo "error: zeekctl start failed" >&2; exit 1; }

# start cron
crond -b -L /dev/fd/1 || { echo "error: failed to start crond" >&2; exit 1; }
echo "cron enabled"

# keep the container running while remaining responsive to signals.
# backgrounding sleep and using wait allows bash to process SIGTERM traps.
# without this, bash blocks on the foreground sleep and never runs the trap.
sleep infinity &
wait $!
