FROM alpine:3.21 AS builder

ARG ZEEK_VERSION=8.0.6
ARG BUILD_PROCS=4

ARG VERSION
RUN test -n "${VERSION}" || { echo "VERSION build-arg required (use: make docker-build VERSION=...)" >&2; exit 1; }

RUN apk add --no-cache zlib openssl libstdc++ libpcap libgcc libzmq
RUN apk add --no-cache -t .build-deps \
    bsd-compat-headers \
    libmaxminddb-dev \
    linux-headers \
    openssl-dev \
    libpcap-dev \
    python3-dev \
    zeromq-dev \
    cppzmq \
    zlib-dev \
    flex-dev \
    binutils \
    bind-dev \
    fts-dev \
    cmake \
    bison \
    bash \
    swig \
    perl \
    make \
    flex \
    git \
    gcc \
    g++ \
    fts \
    krb5-dev \
    py3-gitpython \
    py3-semantic-version

RUN cd /tmp \
    && git clone --recursive --branch v$ZEEK_VERSION https://github.com/zeek/zeek.git

RUN cd /tmp/zeek \
    && CC=gcc ./configure --prefix=/usr/local/zeek \
    --build-type=Release \
    --disable-auxtools \
    --disable-broker-tests \
    --disable-javascript \
    && make -j $BUILD_PROCS \
    && make install

RUN strip -s /usr/local/zeek/bin/zeek

# install packages in the builder to include in the final image
ENV PATH=$PATH:/usr/local/zeek/bin
RUN zkg refresh \
    && zkg install --force ja3 \
    && zkg install --force --version v0.18.8 zeek/foxio/ja4 \
    && zkg install --force --version v1.3.0 zeek-open-connections

FROM alpine:3.21 AS final

ARG VERSION

# python3 and bash are needed for zeekctl scripts
# ethtool is needed to manage interface features
# util-linux provides taskset for CPU pinning
# libzmq is required at runtime even when using Broker as cluster backend
# git, py3-gitpython, py3-semantic-version are needed for runtime zkg
RUN apk --no-cache add \
    ca-certificates zlib openssl libstdc++ libpcap libmaxminddb libgcc fts krb5-libs libzmq \
    python3 bash \
    ethtool \
    util-linux \
    git py3-gitpython py3-semantic-version

COPY --from=builder /usr/local/zeek /usr/local/zeek

ENV ZEEKPATH=.:/usr/local/zeek/share/zeek:/usr/local/zeek/share/zeek/policy:/usr/local/zeek/share/zeek/site
ENV PATH=$PATH:/usr/local/zeek/bin

# zeekctl cron heals crashed processes every 5 minutes
RUN echo "*/5       *       *       *       *       /usr/local/zeek/bin/zeekctl cron" >> /etc/crontabs/root
COPY docker-entrypoint.sh /docker-entrypoint.sh

# node.cfg is generated by the entrypoint
RUN rm -f /usr/local/zeek/etc/node.cfg
COPY etc/networks.cfg /usr/local/zeek/etc/networks.cfg
COPY etc/zeekctl.cfg /usr/local/zeek/etc/zeekctl.cfg
COPY scripts/ /usr/local/zeek/share/zeek/site/autoload/

RUN IMAGE_TAG="${VERSION#v}" && \
    sed -i "s/__VERSION__/${VERSION}/g; s/__IMAGE_TAG__/${IMAGE_TAG}/g" \
    /usr/local/zeek/etc/networks.cfg \
    /usr/local/zeek/etc/zeekctl.cfg \
    /usr/local/zeek/share/zeek/site/autoload/100-default.zeek \
    /usr/local/zeek/share/zeek/site/autoload/200-inactivity_timeout.zeek \
    /usr/local/zeek/share/zeek/site/autoload/900-zkg.zeek \
    /docker-entrypoint.sh

HEALTHCHECK --interval=60s --timeout=5s --retries=3 --start-period=30s \
  CMD pgrep -f /usr/local/zeek/bin/zeek > /dev/null || exit 1

ENTRYPOINT ["/docker-entrypoint.sh"]
