ARG ALPINE_VERSION
ARG ZEEK_VERSION

FROM alpine:${ALPINE_VERSION} AS builder

ARG ZEEK_VERSION
ARG BUILD_PROCS=4

RUN apk add --no-cache zlib openssl libstdc++ libpcap libgcc libzmq
RUN apk add --no-cache -t .build-deps \
    bsd-compat-headers \
    libmaxminddb-dev \
    linux-headers \
    openssl-dev \
    libpcap-dev \
    python3-dev \
    zeromq-dev \
    cppzmq \
    zlib-dev \
    flex-dev \
    binutils \
    bind-dev \
    fts-dev \
    cmake \
    bison \
    bash \
    swig \
    perl \
    make \
    flex \
    git \
    gcc \
    g++ \
    fts \
    krb5-dev

RUN cd /tmp \
    && git clone --recursive --branch v$ZEEK_VERSION https://github.com/zeek/zeek.git

RUN cd /tmp/zeek \
    && CC=gcc ./configure --prefix=/usr/local/zeek \
    --build-type=Release \
    --disable-auxtools \
    --disable-broker-tests \
    --disable-javascript \
    && make -j $BUILD_PROCS \
    && make install

RUN strip -s /usr/local/zeek/bin/zeek

FROM alpine:${ALPINE_VERSION} AS final

# python3 and bash are needed for zeekctl scripts
# ethtool is needed to manage interface features
# util-linux provides taskset for CPU pinning
# libzmq is required at runtime even when using Broker as cluster backend
# py3-pip and git are needed for zkg
RUN apk --no-cache add \
    ca-certificates zlib openssl libstdc++ libpcap libmaxminddb libgcc fts krb5-libs libzmq \
    python3 bash \
    ethtool \
    util-linux \
    py3-pip git

COPY --from=builder /usr/local/zeek /usr/local/zeek

ENV ZEEKPATH=.:/usr/local/zeek/share/zeek:/usr/local/zeek/share/zeek/policy:/usr/local/zeek/share/zeek/site
ENV PATH=$PATH:/usr/local/zeek/bin

ARG ZKG_VERSION=3.1.0
RUN pip install --break-system-packages zkg==$ZKG_VERSION \
    && zkg autoconfig \
    && zkg refresh \
    && zkg install --force ja3 \
    && zkg install --force --version v0.18.8 zeek/foxio/ja4 \
    && zkg install --force --version v1.3.0 zeek-open-connections

# zeekctl cron heals crashed processes every 5 minutes
RUN echo "*/5       *       *       *       *       /usr/local/zeek/bin/zeekctl cron" >> /etc/crontabs/root
COPY docker-entrypoint.sh /docker-entrypoint.sh

# node.cfg is generated by the host-side CLI tool
RUN rm -f /usr/local/zeek/etc/node.cfg
COPY etc/networks.cfg /usr/local/zeek/etc/networks.cfg
COPY etc/zeekctl.cfg /usr/local/zeek/etc/zeekctl.cfg
COPY scripts/ /usr/local/zeek/share/zeek/site/autoload/

HEALTHCHECK --interval=60s --timeout=5s --retries=3 --start-period=30s \
  CMD pgrep -f /usr/local/zeek/bin/zeek > /dev/null || exit 1

ENTRYPOINT ["/docker-entrypoint.sh"]
