package docker

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	ContainerName = "zeek"
	DefaultImage  = "activecm/zeek"
	HeaderMarker  = "Generated by docker-zeek "
)

var ErrInvalidPath = errors.New("invalid path")

// ContainerState holds the running state of the zeek container
type ContainerState struct {
	Running bool
	Image   string
}

// WarnLegacyVolumes prints a notice if named volumes from a previous version still exist on the host
func WarnLegacyVolumes() {
	legacy := []string{"zeek-zkg-script", "zeek-zkg-plugin", "zeek-zkg-state"}
	var present []string
	for _, v := range legacy {
		if _, err := dockerCmd(true, "volume", "inspect", v); err == nil {
			present = append(present, v)
		}
	}
	if len(present) == 0 {
		return
	}
	fmt.Fprintln(os.Stderr, "warning: legacy zkg volumes from a previous version are still present:")
	for _, v := range present {
		fmt.Fprintf(os.Stderr, "  %s\n", v)
	}
	fmt.Fprintf(os.Stderr, "To remove them:\n  docker volume rm %s\n", strings.Join(present, " "))
	fmt.Fprintln(os.Stderr, "If you had custom Zeek packages installed, see:")
	fmt.Fprintln(os.Stderr, "  https://github.com/activecm/docker-zeek#migrating-from-older-versions")
}

// Inspect returns the state of the zeek container
func Inspect() (*ContainerState, error) {
	out, err := dockerCmd(true, "ps", "-a", "--filter", "name=^/"+ContainerName+"$", "--format", "{{.State}}|{{.Image}}")
	if err != nil {
		return nil, fmt.Errorf("checking container state: %w", err)
	}
	line := strings.TrimSpace(out)
	if line == "" {
		return nil, nil
	}
	state, image, _ := strings.Cut(line, "|")
	return &ContainerState{Running: state == "running", Image: image}, nil
}

// Stop stops and removes the zeek container
func Stop() error {
	state, err := Inspect()
	if err != nil {
		return err
	}
	if state == nil {
		fmt.Fprintln(os.Stderr, "Zeek is already stopped.")
		return nil
	}
	if state.Running {
		fmt.Fprintln(os.Stderr, "Stopping the Zeek container")
		if _, err := dockerCmd(false, "stop", "-t", "90", ContainerName); err != nil {
			return err
		}
	} else {
		fmt.Fprintln(os.Stderr, "Zeek is already stopped.")
	}
	// if container exists, attempt to remove it but ignore errors
	_, _ = dockerCmd(false, "rm", "--force", ContainerName)
	return nil
}

// Start starts the zeek container
func Start(image, hostDir string, envVars map[string]string) error {
	state, err := Inspect()
	if err != nil {
		return err
	}
	if state != nil && state.Running {
		fmt.Fprintln(os.Stderr, "Zeek is already running.")
		return nil
	}
	// remove any stale stopped container with the same name so docker run does not collide
	if state != nil {
		if _, err := dockerCmd(false, "rm", ContainerName); err != nil {
			return fmt.Errorf("removing stale container: %w", err)
		}
	}

	args := buildRunArgs(image, hostDir, "unless-stopped", envVars)
	fmt.Fprintln(os.Stderr, "Starting the Zeek container")
	_, err = dockerCmd(false, args...)
	return err
}

// ReadPCAP runs zeek against a pcap file and writes logs to the given output directory
func ReadPCAP(image, hostDir, pcapPath, logDir string) error {
	absPcap, err := filepath.Abs(pcapPath)
	if err != nil {
		return fmt.Errorf("resolving pcap path: %w", err)
	}

	absLogDir, err := filepath.Abs(logDir)
	if err != nil {
		return fmt.Errorf("resolving log directory: %w", err)
	}

	args := buildReadPCAPArgs(image, hostDir, absPcap, absLogDir)
	fmt.Fprintln(os.Stderr, "Starting the Zeek container")
	fmt.Fprintf(os.Stderr, "Zeek logs will be saved to %s\n", absLogDir)
	_, err = dockerCmd(false, args...)
	return err
}

// Status prints the status of the zeek container and zeekctl processes
func Status() error {
	fmt.Fprintln(os.Stderr, "Zeek container status")
	state, err := Inspect()
	if err != nil {
		return err
	}
	if state == nil || !state.Running {
		fmt.Fprintln(os.Stderr, "Zeek is not running.")
		return nil
	}
	out, err := dockerCmd(false, "ps", "--filter", "name=^zeek$")
	if err == nil && out != "" {
		fmt.Println(out)
	}
	fmt.Fprintln(os.Stderr, "Zeek processes status")
	out, err = dockerCmd(false, "exec", ContainerName, "zeekctl", "status")
	if err == nil && out != "" {
		fmt.Println(out)
	}
	return err
}

// InitHostDir creates the host directory and installs or updates managed config files.
func InitHostDir(image, hostDir, version string) error {
	container := fmt.Sprintf("zeek-init-%d", os.Getpid())

	// remove any orphaned init containers from previously interrupted runs
	if out, _ := dockerCmd(true, "ps", "-aq", "--filter", "name=^/zeek-init-"); out != "" {
		for _, id := range strings.Fields(out) {
			_, _ = dockerCmd(true, "rm", "--force", id)
		}
	}

	// start a temporary container
	// override the entrypoint since it expects node.cfg, which doesn't exist yet
	_, err := dockerCmd(false,
		"run", "--detach",
		"--ulimit", "nofile=1048576:1048576",
		"--name", container,
		"-v", hostDir+":/zeek",
		"--network", "none",
		"--entrypoint", "sh",
		image,
		"-c", "while sleep 1; do :; done",
	)
	if err != nil {
		return fmt.Errorf("starting init container: %w", err)
	}

	// ensure cleanup
	defer func() { _, _ = dockerCmd(false, "rm", "--force", container) }()

	// create directories
	dirs := []string{
		"/zeek/manual-logs",
		"/zeek/logs",
		"/zeek/spool",
		"/zeek/etc",
		"/zeek/share/zeek/site/autoload",
	}
	mkdirArgs := append([]string{"exec", container, "mkdir", "-p"}, dirs...)
	if _, err = dockerCmd(false, mkdirArgs...); err != nil {
		return fmt.Errorf("creating host directories: %w", err)
	}

	// set permissions on log directories
	chmodArgs := []string{"exec", container, "chmod", "-f", "0755",
		"/zeek/manual-logs", "/zeek/logs", "/zeek/spool"}
	if _, err = dockerCmd(false, chmodArgs...); err != nil {
		return fmt.Errorf("setting directory permissions: %w", err)
	}

	// install networks.cfg if missing, otherwise leave it alone
	networksPath := filepath.Join(hostDir, "etc/networks.cfg")
	if _, err := os.Stat(networksPath); errors.Is(err, os.ErrNotExist) {
		if err := cpFromContainer(container, "/usr/local/zeek/etc/networks.cfg", "/zeek/etc/networks.cfg"); err != nil {
			return err
		}
	} else if err != nil {
		return fmt.Errorf("checking networks.cfg: %w", err)
	}

	// user-editable files
	if err = handleUserEditable(container, hostDir, version, "etc/zeekctl.cfg", "/usr/local/zeek/etc/zeekctl.cfg"); err != nil {
		return err
	}
	if err = handleUserEditable(container, hostDir, version, "share/zeek/site/autoload/100-default.zeek", "/usr/local/zeek/share/zeek/site/autoload/100-default.zeek"); err != nil {
		return err
	}

	// system-managed files
	if err = handleSystemManaged(container, hostDir, version, "share/zeek/site/autoload/200-inactivity_timeout.zeek", "/usr/local/zeek/share/zeek/site/autoload/200-inactivity_timeout.zeek"); err != nil {
		return err
	}
	if err = handleSystemManaged(container, hostDir, version, "share/zeek/site/autoload/900-zkg.zeek", "/usr/local/zeek/share/zeek/site/autoload/900-zkg.zeek"); err != nil {
		return err
	}

	// clean up 001-unload-scripts.zeek from older versions if it's still on the host
	if _, err = dockerCmd(false, "exec", container, "rm", "-f",
		"/zeek/share/zeek/site/autoload/001-unload-scripts.zeek"); err != nil {
		return fmt.Errorf("removing stale autoload scripts: %w", err)
	}

	// archive any existing host local.zeek
	if err := archiveLocalZeek(hostDir); err != nil {
		return err
	}

	return nil
}

// readHeaderVersion reads the docker-zeek version from a file's header
func readHeaderVersion(path string) (string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	scanner := bufio.NewScanner(bytes.NewReader(content))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		if idx := strings.Index(line, HeaderMarker); idx >= 0 {
			return strings.TrimSpace(line[idx+len(HeaderMarker):]), nil
		}
		return "", nil
	}
	return "", scanner.Err()
}

// handleUserEditable handles a user-editable config file
//   - missing or empty file gets installed fresh
//   - file with current version is left alone
//   - legacy file without version header gets renamed to .bak and new file installed
//   - file with different version header gets left alone and new file installed as .new for manual review
func handleUserEditable(container, hostDir, currentVersion, relPath, containerPath string) error {
	hostPath := filepath.Join(hostDir, relPath)
	info, err := os.Stat(hostPath)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("checking %s: %w", relPath, err)
	}

	var message string
	dest := "/zeek/" + relPath

	if err == nil && info.Size() > 0 {
		headerVer, err := readHeaderVersion(hostPath)
		if err != nil {
			return fmt.Errorf("reading header of %s: %w", relPath, err)
		}

		switch headerVer {
		case currentVersion:
			return nil
		case "": // legacy file
			if err := os.Rename(hostPath, hostPath+".bak"); err != nil {
				return fmt.Errorf("renaming legacy %s: %w", relPath, err)
			}
			message = fmt.Sprintf("Renamed legacy %s to %s.bak. Review and copy any settings to the new file.", relPath, relPath)
		default: // version mismatch: install as .new, leave live alone
			dest = "/zeek/" + relPath + ".new"
			message = fmt.Sprintf("Updated defaults at %s.new. Please review and merge into %s, then restart zeek.", relPath, relPath)
		}
	}

	if err := cpFromContainer(container, containerPath, dest); err != nil {
		return err
	}
	if message != "" {
		fmt.Fprintln(os.Stderr, message)
	}
	return nil
}

// handleSystemManaged handles a system-managed config file
//   - missing or empty file gets installed fresh
//   - file with current version is left alone
//   - any other state gets overwritten
func handleSystemManaged(container, hostDir, currentVersion, relPath, containerPath string) error {
	hostPath := filepath.Join(hostDir, relPath)
	info, err := os.Stat(hostPath)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("checking %s: %w", relPath, err)
	}

	if err == nil && info.Size() > 0 {
		headerVer, err := readHeaderVersion(hostPath)
		if err != nil {
			return fmt.Errorf("reading header of %s: %w", relPath, err)
		}
		if headerVer == currentVersion {
			return nil
		}
	}

	return cpFromContainer(container, containerPath, "/zeek/"+relPath)
}

// cpFromContainer copies a file from the container to the host
func cpFromContainer(container, src, dest string) error {
	if _, err := dockerCmd(false, "exec", container, "cp", "-f", src, dest); err != nil {
		return fmt.Errorf("copying %s to %s in container: %w", src, dest, err)
	}
	return nil
}

// archiveLocalZeek renames an existing host local.zeek to local.zeek.bak
func archiveLocalZeek(hostDir string) error {
	path := filepath.Join(hostDir, "share", "zeek", "site", "local.zeek")
	info, err := os.Stat(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return err
	}
	if info.Size() == 0 {
		return nil
	}
	fmt.Fprintln(os.Stderr, "Found existing local.zeek, moving to local.zeek.bak. docker-zeek auto-generates this file.")
	return os.Rename(path, path+".bak")
}

func buildRunArgs(image, hostDir, restart string, envVars map[string]string) []string {
	args := []string{
		"run", "--detach",
		"--ulimit", "nofile=1048576:1048576",
		"--name", ContainerName,
		"--restart", restart,
		"--cap-add", "net_raw",
		"--cap-add", "net_admin",
		"--network", "host",
	}

	// timezone
	args = append(args, bindMount("/etc/localtime", "/etc/localtime", true)...)

	// logs and spool
	args = append(args, bindMount(filepath.Join(hostDir, "logs"), "/usr/local/zeek/logs/", false)...)
	args = append(args, bindMount(filepath.Join(hostDir, "spool"), "/usr/local/zeek/spool/", false)...)

	// configs
	args = append(args, findAndMount(filepath.Join(hostDir, "etc"), hostDir, false)...)

	// scripts
	args = append(args, findAndMountZeekScripts(hostDir)...)

	// env vars
	for k, v := range envVars {
		args = append(args, "-e", fmt.Sprintf("%s=%s", k, v))
	}

	args = append(args, image)
	return args
}

func buildReadPCAPArgs(image, hostDir, pcapPath, logDir string) []string {
	args := []string{
		"run", "--rm",
		"--ulimit", "nofile=1048576:1048576",
		"--workdir", "/usr/local/zeek/logs/",
	}

	// timezone
	args = append(args, bindMount("/etc/localtime", "/etc/localtime", true)...)

	// output logs
	args = append(args, bindMount(logDir, "/usr/local/zeek/logs/", false)...)

	// pcap
	args = append(args, bindMount(pcapPath, "/incoming.pcap", true)...)

	// configs
	args = append(args, findAndMount(filepath.Join(hostDir, "etc"), hostDir, false)...)

	// scripts
	args = append(args, findAndMountZeekScripts(hostDir)...)

	args = append(args, "--entrypoint", "/bin/bash", image, "-c", buildReadPCAPCommand())

	return args
}

func buildReadPCAPCommand() string {
	parts := []string{
		// generate local.zeek from autoload partials
		`grep -hv '^#' /usr/local/zeek/share/zeek/site/autoload/*.zeek > /usr/local/zeek/share/zeek/site/local.zeek`,
		// disable af_packet plugin for pcap reading. subshell isolates the || true
		`(mv -f /usr/local/zeek/share/zeek/builtin-plugins/Zeek_AF_Packet/{__load__.zeek,init.zeek} /usr/local/zeek/share/zeek/builtin-plugins/ 2>/dev/null || true)`,
		// run zeek. empty Notice::sendmail mutes mail. process substitution filters the 'Node names' warning while keeping zeek's exit code.
		`/usr/local/zeek/bin/zeek -C -r /incoming.pcap local 'Site::local_nets += { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 }' 'Notice::sendmail = ' 2> >(grep -v 'Node names are not added to logs (not in cluster mode' >&2)`,
	}
	return strings.Join(parts, " && ")
}

// ValidatePath checks that a path is safe to use as a docker --mount source
func ValidatePath(p string) error {
	p = strings.TrimSpace(p)
	if p == "" {
		return fmt.Errorf("%w: empty", ErrInvalidPath)
	}
	if !filepath.IsAbs(p) {
		return fmt.Errorf("%w: must be absolute: %q", ErrInvalidPath, p)
	}
	// detect traversal before filepath.Clean resolves it away
	for _, part := range strings.Split(filepath.ToSlash(p), "/") {
		if part == ".." {
			return fmt.Errorf("%w: contains traversal element: %q", ErrInvalidPath, p)
		}
	}
	if strings.ContainsAny(p, ",=") {
		return fmt.Errorf("%w: contains character disallowed by docker --mount: %q", ErrInvalidPath, p)
	}
	return nil
}

// bindMount returns the docker run arguments to bind mount a file or directory into the container
func bindMount(src, dest string, readonly bool) []string {
	mount := fmt.Sprintf("source=%s,destination=%s,type=bind", src, dest)
	if readonly {
		mount += ",readonly"
	}
	return []string{"--mount", mount}
}

// findAndMount mounts all files in a directory into the container
func findAndMount(dir, hostDir string, readonly bool) []string {
	var args []string
	entries, err := filepath.Glob(filepath.Join(dir, "*"))
	if err != nil {
		return args
	}
	for _, entry := range entries {
		info, err := os.Lstat(entry)
		if err != nil || info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
			continue
		}
		rel, _ := filepath.Rel(hostDir, entry)
		dest := "/usr/local/zeek/" + rel
		args = append(args, bindMount(entry, dest, readonly)...)
	}
	return args
}

// findAndMountZeekScripts mounts .zeek files from the host's autoload directory into the container
func findAndMountZeekScripts(hostDir string) []string {
	var args []string
	autoload := filepath.Join(hostDir, "share/zeek/site/autoload")
	entries, err := os.ReadDir(autoload)
	if err != nil {
		return args
	}
	for _, entry := range entries {
		if entry.IsDir() || entry.Type()&fs.ModeSymlink != 0 {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(strings.ToLower(name), ".zeek") || name == "local.zeek" {
			continue
		}
		path := filepath.Join(autoload, name)
		rel, _ := filepath.Rel(hostDir, path)
		dest := "/usr/local/zeek/" + rel
		args = append(args, bindMount(path, dest, false)...)
	}
	return args
}

// dockerCmd runs a docker command. If quiet, stderr is captured but not echoed to the terminal
func dockerCmd(quiet bool, args ...string) (string, error) {
	cmd := exec.Command("docker", args...)

	var stderr bytes.Buffer
	if quiet {
		cmd.Stderr = &stderr
	} else {
		cmd.Stdin = os.Stdin
		cmd.Stderr = io.MultiWriter(os.Stderr, &stderr)
	}

	out, err := cmd.Output()
	if err != nil {
		return strings.TrimSpace(stderr.String()), err
	}
	return strings.TrimSpace(string(out)), nil
}
