##! Generated by docker-zeek __VERSION__
##!
##! DO NOT EDIT. Changes to this file will not be preserved.
##! For custom Zeek code, add a separate .zeek file in this directory.

# Zeek's default tcp_inactivity_timeout is 5 min, which splits quiet-but-live
# TCP sessions into multiple conn.log records. 1 hour keeps long connections
# as a single record at the cost of holding state longer in memory.
redef tcp_inactivity_timeout = 60 min;
