##! Generated by docker-zeek __VERSION__
##!
##! DO NOT EDIT. Changes to this file will not be preserved.
##! For custom Zeek code, add a separate .zeek file in this directory.

# Auto load installed packages from the Zeek package manager
@load packages
