name: Update Docker Description

on:
  push:
    # https://github.com/peter-evans/dockerhub-description/issues/10
    branches: [disabled] # purposely disabled as this doesn't work with Docker access tokens
    paths:
      - '.github/workflows/docker-description.yml'
      - 'Readme.md'

jobs:
  description:
    name: Update Docker Zeek description
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: activecm/zeek
          readme-filepath: ./Readme.md