name: Update Docker Description

on:
  push:
    branches: [ master, build ]
    paths:
      - '.github/workflows/docker-description.yml'
      - 'Readme.md'

jobs:
  description:
    name: Update Docker Zeek description
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: activecm/zeek
          readme-filepath: ./Readme.md