name: Integration Tests

# this workflow is only triggered manually as it is relatively slow and resource intensive

on:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build Docker image
        run: |
          make docker-build
          source build.env
          docker tag activecm/zeek:${ZEEK_VERSION} activecm/zeek:integration-test

      - name: Download Go dependencies
        run: go mod download

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run integration tests
        run: gotestsum --format pkgname --junitfile integration-results.xml -- -tags integration ./integration/... -count=1 -timeout 30m

      - name: Integration test report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: integration-results.xml
          update_check: true
          include_passed: true
          job_name: integration-tests
